# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cartReg <- function(y, x, max_depth, min_samples_leaf, min_samples_split, min_ig) {
    .Call(`_cartlm_cartReg`, y, x, max_depth, min_samples_leaf, min_samples_split, min_ig)
}

predictCart <- function(model, X, method = "mean") {
    .Call(`_cartlm_predictCart`, model, X, method)
}

